# Generated by Django 3.1.13 on 2021-11-03 10:54

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='open', max_length=100, no_check_for_status=True),
        ),
    ]
